[2022-09-14 14:33:00,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:31:06.970320+00:00 [queued]>
[2022-09-14 14:33:00,867] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:31:06.970320+00:00 [queued]>
[2022-09-14 14:33:00,868] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:33:00,869] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-09-14 14:33:00,870] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:33:00,884] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-09-14 14:31:06.970320+00:00
[2022-09-14 14:33:00,890] {standard_task_runner.py:52} INFO - Started process 258 to run task
[2022-09-14 14:33:00,894] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'manual__2022-09-14T14:31:06.970320+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmphz75nzt0', '--error-file', '/tmp/tmp96h5jjxk']
[2022-09-14 14:33:00,895] {standard_task_runner.py:80} INFO - Job 39: Subtask parser_python
[2022-09-14 14:33:00,934] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:31:06.970320+00:00 [running]> on host c0f73d32ee2c
[2022-09-14 14:33:00,982] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T14:31:06.970320+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T14:31:06.970320+00:00
[2022-09-14 14:33:13,636] {logging_mixin.py:115} INFO - No more products in 5ka
[2022-09-14 14:33:26,415] {logging_mixin.py:115} INFO - No more products in magnit-univer
[2022-09-14 14:33:38,567] {logging_mixin.py:115} INFO - No more products in perekrestok
[2022-09-14 14:33:47,711] {logging_mixin.py:115} INFO - No more products in dixy
[2022-09-14 14:34:01,910] {logging_mixin.py:115} INFO - No more products in lenta-super
[2022-09-14 14:34:15,529] {logging_mixin.py:115} INFO - No more products in vkusvill_offline
[2022-09-14 14:34:26,983] {logging_mixin.py:115} INFO - No more products in mgnl
[2022-09-14 14:34:27,134] {logging_mixin.py:115} INFO - No data for azbuka_vkusa
[2022-09-14 14:34:27,140] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 93, in final
    with open('prices_data/prices.pickle', 'wb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'prices_data/prices.pickle'
[2022-09-14 14:34:27,158] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20220914T143106, start_date=20220914T143300, end_date=20220914T143427
[2022-09-14 14:34:27,173] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task parser_python ([Errno 2] No such file or directory: 'prices_data/prices.pickle'; 258)
[2022-09-14 14:34:27,204] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 14:34:27,233] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
