[2022-09-14 14:33:04,960] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:33:04.411536+00:00 [queued]>
[2022-09-14 14:33:04,966] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:33:04.411536+00:00 [queued]>
[2022-09-14 14:33:04,967] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:33:04,967] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-14 14:33:04,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 14:33:04,976] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-09-14 14:33:04.411536+00:00
[2022-09-14 14:33:04,982] {standard_task_runner.py:52} INFO - Started process 260 to run task
[2022-09-14 14:33:04,985] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'manual__2022-09-14T14:33:04.411536+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmpae8lpfd8', '--error-file', '/tmp/tmpvrdnzpmh']
[2022-09-14 14:33:04,986] {standard_task_runner.py:80} INFO - Job 40: Subtask parser_python
[2022-09-14 14:33:05,029] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python manual__2022-09-14T14:33:04.411536+00:00 [running]> on host c0f73d32ee2c
[2022-09-14 14:33:05,076] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T14:33:04.411536+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T14:33:04.411536+00:00
[2022-09-14 14:33:16,878] {logging_mixin.py:115} INFO - No more products in 5ka
[2022-09-14 14:33:28,771] {logging_mixin.py:115} INFO - No more products in magnit-univer
[2022-09-14 14:33:40,133] {logging_mixin.py:115} INFO - No more products in perekrestok
[2022-09-14 14:33:50,192] {logging_mixin.py:115} INFO - No more products in dixy
[2022-09-14 14:34:01,966] {logging_mixin.py:115} INFO - No more products in lenta-super
[2022-09-14 14:34:14,418] {logging_mixin.py:115} INFO - No more products in vkusvill_offline
[2022-09-14 14:34:26,343] {logging_mixin.py:115} INFO - No more products in mgnl
[2022-09-14 14:34:26,504] {logging_mixin.py:115} INFO - No data for azbuka_vkusa
[2022-09-14 14:34:26,506] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 93, in final
    with open('prices_data/prices.pickle', 'wb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'prices_data/prices.pickle'
[2022-09-14 14:34:26,526] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20220914T143304, start_date=20220914T143304, end_date=20220914T143426
[2022-09-14 14:34:26,542] {standard_task_runner.py:97} ERROR - Failed to execute job 40 for task parser_python ([Errno 2] No such file or directory: 'prices_data/prices.pickle'; 260)
[2022-09-14 14:34:26,575] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 14:34:26,613] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
