[2022-10-16 22:52:11,106] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-10-16T22:50:26.527337+00:00 [queued]>
[2022-10-16 22:52:11,122] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-10-16T22:50:26.527337+00:00 [queued]>
[2022-10-16 22:52:11,124] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 22:52:11,128] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-10-16 22:52:11,131] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-16 22:52:11,155] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-10-16 22:50:26.527337+00:00
[2022-10-16 22:52:11,170] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2022-10-16 22:52:11,175] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'manual__2022-10-16T22:50:26.527337+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmpk_84eqko', '--error-file', '/tmp/tmp1c3u9wz8']
[2022-10-16 22:52:11,176] {standard_task_runner.py:80} INFO - Job 11: Subtask parser_python
[2022-10-16 22:52:11,228] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python manual__2022-10-16T22:50:26.527337+00:00 [running]> on host eda31ed78ba3
[2022-10-16 22:52:11,306] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-10-16T22:50:26.527337+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-16T22:50:26.527337+00:00
[2022-10-16 22:52:12,473] {logging_mixin.py:115} INFO - No more products in 5ka
[2022-10-16 22:52:22,168] {logging_mixin.py:115} INFO - No more products in magnit-univer
[2022-10-16 22:52:32,101] {logging_mixin.py:115} INFO - No more products in perekrestok
[2022-10-16 22:52:38,758] {logging_mixin.py:115} INFO - No more products in dixy
[2022-10-16 22:52:39,438] {logging_mixin.py:115} INFO - No more products in lenta-super
[2022-10-16 22:52:50,336] {logging_mixin.py:115} INFO - No more products in vkusvill_offline
[2022-10-16 22:53:00,282] {logging_mixin.py:115} INFO - No more products in mgnl
[2022-10-16 22:53:00,385] {logging_mixin.py:115} INFO - No data for azbuka_vkusa
[2022-10-16 22:53:00,421] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 105, in final
    t_pd = pd.DataFrame(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 465, in dict_to_mgr
    arrays, data_names, index, columns, dtype=dtype, typ=typ, consolidate=copy
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2022-10-16 22:53:00,447] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20221016T225026, start_date=20221016T225211, end_date=20221016T225300
[2022-10-16 22:53:00,466] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task parser_python (All arrays must be of the same length; 183)
[2022-10-16 22:53:00,501] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-16 22:53:00,557] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
